version: '3.7'

x-connections: &commonConnections
    AIRFLOW__CORE__EXECUTOR: 'CeleryExecutor'
    AIRFLOW__CELERY__RESULT_BACKEND: 'db+postgresql://airflow:airflow@postgres:5432/airflow'
    AIRFLOW__CELERY__BROKER_URL: 'redis://redis:6379/1'

x-airflow-environment: &airflowEnvironment
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres:5432/airflow'
    PYTHONPATH: '/opt/airflow/dags'
    AIRFLOW_HOME: '/opt/airflow'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'TRUE'
    AIRFLOW__WEBSERVER__NAVBAR_COLOR: '#bca0dc'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'TRUE'

x-default-user: &defaultUser
    USERNAME: 'admin'
    PASSWORD: 'admin'
    ROLE: 'Admin'
    FIRSTNAME: 'Firstname'
    LASTNAME: 'Lastname'
    EMAIL: 'username@domain.com'

services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow

    redis:
        image: redis:6.0.9-alpine

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
        command: scheduler

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
            - scheduler
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
            <<: *defaultUser
        ports:
            - 8080:8080
        command: webserver

    flower:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - scheduler
            - redis
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
            <<: *defaultUser
        ports:
            - 5555:5555
        command: flower

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
        command: worker
